language: 
  - python
  - node_js

python:
 - "2.7"

node_js:
 - "4.0.0"

env:
  global:
  - API_CHECK=https://appengine.google.com/api/updatecheck

install:
# Idea from https://blog.bekt.net/p/gae-sdk/
- SDK_VERSION=$(curl -s $API_CHECK | awk -F '\"' '/release/ {print $2}')
- SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$SDK_VERSION.zip
- wget $SDK_URL -nv
- unzip -q google_appengine_$SDK_VERSION.zip

# Install dependencies to backend
- mkdir lib
- pip install -t lib -r requirements.txt
- mv lib/google/* google_appengine/google
- rm -rf lib/google
- ls
- ls google_appengine/google
- ls lib
- ls /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/google
- ls /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/google/appengine
- ls /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/google/appengine/ext

before_script:
# - nvm install 4.0.0

# Install dev-dependencies to frontEnd tests
# - cd app/test/
# - npm install
# - cd ../../

# Define display to travis simulate a browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# command to run tests
script: 
    - python -m unittest discover -v -p "*test.py"
    # - cd app/test && ./node_modules/.bin/karma start --browsers Firefox --single-run

notifications:
    slack: e-ciis:5ttYSzVNz0z5XwYRaWBHExyW
