language: 
  - python
  - node_js

python:
 - "2.7"

node_js:
 - "4.0.0"

env:
  global:
  - API_CHECK=https://appengine.google.com/api/updatecheck

install:
- cd backend/
- pip install -r requirements.txt
# Idea from https://blog.bekt.net/p/gae-sdk/
- SDK_VERSION=$(curl -s $API_CHECK | awk -F '\"' '/release/ {print $2}')
- SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$SDK_VERSION.zip
- wget $SDK_URL -nv
- unzip -q google_appengine_$SDK_VERSION.zip

 Install dependencies to backend                                                 
- mkdir lib
- pip install -t lib google-auth==1.1.1 --no-deps
- mv lib/google/* google_appengine/google
- rm -rf lib/google
- cd ../

before_script:
- nvm install 4.0.0

# Install dev-dependencies to frontEnd tests
- cd frontend/test/
- npm install
- npm install -g bower
- bower install
- cd ../../

# Define display to travis simulate a browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# command to run tests
script: 
    - cd backend 
    - python -m unittest discover -v -p "*test.py"
    - cd ../
    - cd frontend/test
    - ./node_modules/.bin/karma start --browsers Firefox --single-run

notifications:
    email: false
    slack: e-cis:5ttYSzVNz0z5XwYRaWBHExyW
