runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1s"

handlers:
- url: /(login|logout)
  script: main.app

- url: /api.*
  script: main.app

- url: /admin.*
  script: admin.app
  login: admin

- url: /
  static_files: app/landingPage/landing_page.html
  upload: app/landingPage/landing_page.html

- url: /app
  script: main.app

- url: /app/
  static_files: app/index.html
  upload: app/index.html

- url: (.*)
  static_files: app\1
  upload: app/(.*)